import { AppState, Habit, Player, Stake } from './types';
import { getMonthKey, getTodayDateString, getWeekKey } from './date-utils';

export const INITIAL_PLAYERS: Record<'maciek' | 'myrna', Player> = {
  maciek: {
    id: 'maciek',
    name: 'Maciek',
    avatar: '⚡',
    color: '#60a5fa', // Linear sky blue
    accentBg: 'rgba(96, 165, 250, 0.1)',
    accentBorder: 'rgba(96, 165, 250, 0.25)',
  },
  myrna: {
    id: 'myrna',
    name: 'Myrna',
    avatar: '✨',
    color: '#f472b6', // Linear rose pink
    accentBg: 'rgba(244, 114, 182, 0.1)',
    accentBorder: 'rgba(244, 114, 182, 0.25)',
  },
};

export const INITIAL_HABITS: Habit[] = [
  // --- Maciek's Habits ---
  {
    id: 'maciek-sleep',
    playerId: 'maciek',
    title: 'Sleep 8+ Hours',
    description: 'Rest & recovery tracked via Fitbit / Health Connect',
    category: 'foundation',
    points: 50,
    iconName: 'Moon',
    order: 1,
    isActive: true,
  },
  {
    id: 'maciek-gym',
    playerId: 'maciek',
    title: 'Gym & Strength',
    description: 'Heavy lifting or strength workout (Hevy / Welltory)',
    category: 'physical',
    points: 40,
    iconName: 'Dumbbell',
    frequency: 'weekly',
    weeklyTargetDays: 4,
    order: 2,
    isActive: true,
  },
  {
    id: 'maciek-sport',
    playerId: 'maciek',
    title: 'Basketball or Run',
    description: 'High intensity cardio or basketball (Strava)',
    category: 'cardio',
    points: 30,
    iconName: 'Flame',
    frequency: 'weekly',
    weeklyTargetDays: 3,
    order: 3,
    isActive: true,
  },
  {
    id: 'maciek-reading',
    playerId: 'maciek',
    title: 'Read Books',
    description: '1 point per page read (up to 25 pts maximum)',
    category: 'intellect',
    points: 25,
    iconName: 'BookOpen',
    isQuantitative: true,
    quantityUnit: 'pages',
    maxQuantity: 25,
    pointsPerUnit: 1,
    order: 4,
    isActive: true,
  },
  {
    id: 'maciek-project',
    playerId: 'maciek',
    title: 'Personal Project',
    description: 'Deep work building tangible product / code',
    category: 'deep_work',
    points: 25,
    iconName: 'Code',
    order: 5,
    isActive: true,
  },
  {
    id: 'maciek-skills',
    playerId: 'maciek',
    title: 'Skills (Design / Code / Maths)',
    description: '30m deliberate craft practice (Graphic design, code, math)',
    category: 'skills',
    points: 25,
    iconName: 'Target',
    order: 6,
    isActive: true,
  },
  {
    id: 'maciek-nutrition',
    playerId: 'maciek',
    title: 'Eat Healthy',
    description: 'Whole foods, balanced nutrition, zero junk snacking',
    category: 'nutrition',
    points: 15,
    iconName: 'Apple',
    order: 7,
    isActive: true,
  },
  {
    id: 'maciek-clean',
    playerId: 'maciek',
    title: 'Clean Space',
    description: 'Organized and clean living/working environment',
    category: 'environment',
    points: 15,
    iconName: 'CheckCircle2',
    requiresProof: true,
    order: 8,
    isActive: true,
  },
  {
    id: 'maciek-mind',
    playerId: 'maciek',
    title: 'Prayer & Meditation',
    description: 'Spiritual stillness and mental grounding (Medito / Prayer)',
    category: 'mind',
    points: 10,
    iconName: 'Sparkles',
    order: 9,
    isActive: true,
  },
  {
    id: 'maciek-language',
    playerId: 'maciek',
    title: 'Swedish (Duolingo / Speaking)',
    description: 'Duolingo lesson or conversational practice with Myrna',
    category: 'language',
    points: 5,
    iconName: 'Globe',
    order: 10,
    isActive: true,
  },

  // --- Myrna's Habits ---
  {
    id: 'myrna-sleep',
    playerId: 'myrna',
    title: 'Sleep 8+ Hours',
    description: 'Rest & recovery tracked via Garmin / wearable',
    category: 'foundation',
    points: 50,
    iconName: 'Moon',
    order: 1,
    isActive: true,
  },
  {
    id: 'myrna-gym',
    playerId: 'myrna',
    title: 'Gym & Strength',
    description: 'Workout at The Gym Group / Hevy session',
    category: 'physical',
    points: 40,
    iconName: 'Dumbbell',
    frequency: 'weekly',
    weeklyTargetDays: 4,
    order: 2,
    isActive: true,
  },
  {
    id: 'myrna-sport',
    playerId: 'myrna',
    title: 'Running',
    description: 'Outdoor or treadmill run (Strava / Garmin)',
    category: 'cardio',
    points: 30,
    iconName: 'Footprints',
    frequency: 'weekly',
    weeklyTargetDays: 3,
    order: 3,
    isActive: true,
  },
  {
    id: 'myrna-reading',
    playerId: 'myrna',
    title: 'Read Books',
    description: '1 point per page read (up to 25 pts maximum)',
    category: 'intellect',
    points: 25,
    iconName: 'BookOpen',
    isQuantitative: true,
    quantityUnit: 'pages',
    maxQuantity: 25,
    pointsPerUnit: 1,
    order: 4,
    isActive: true,
  },
  {
    id: 'myrna-project',
    playerId: 'myrna',
    title: 'Personal Project',
    description: 'Dedicated progress on personal creative/work project',
    category: 'deep_work',
    points: 25,
    iconName: 'Briefcase',
    order: 5,
    isActive: true,
  },
  {
    id: 'myrna-skills',
    playerId: 'myrna',
    title: 'Skills (Design / Craft / Learning)',
    description: '30m focused practice expanding skill set',
    category: 'skills',
    points: 25,
    iconName: 'Target',
    order: 6,
    isActive: true,
  },
  {
    id: 'myrna-nutrition',
    playerId: 'myrna',
    title: 'Eat Healthy',
    description: 'Clean whole nutrition and fueling the body well',
    category: 'nutrition',
    points: 15,
    iconName: 'Apple',
    order: 7,
    isActive: true,
  },
  {
    id: 'myrna-clean',
    playerId: 'myrna',
    title: 'Clean Space',
    description: 'Tidy, organized personal space & bedroom',
    category: 'environment',
    points: 15,
    iconName: 'CheckCircle2',
    requiresProof: true,
    order: 8,
    isActive: true,
  },
  {
    id: 'myrna-mind',
    playerId: 'myrna',
    title: 'Meditate & Red Light',
    description: 'Mindfulness session and red light therapy rejuvenation',
    category: 'mind',
    points: 10,
    iconName: 'Sun',
    order: 9,
    isActive: true,
  },
  {
    id: 'myrna-language',
    playerId: 'myrna',
    title: 'Polish (Duolingo / Speaking)',
    description: 'Duolingo lesson or conversational practice with Maciek',
    category: 'language',
    points: 5,
    iconName: 'Globe',
    order: 10,
    isActive: true,
  },
];

export function getInitialStakes(): Stake[] {
  const today = getTodayDateString();
  const currentWeek = getWeekKey(today);
  const currentMonth = getMonthKey(today);

  return [
    {
      id: 'stake-week-current',
      period: 'weekly',
      periodKey: currentWeek,
      title: 'Sunday Dinner Date 🍕',
      description: 'Winner chooses favorite restaurant, loser picks up the tab!',
      status: 'active',
      dueDate: today,
    },
    {
      id: 'stake-month-current',
      period: 'monthly',
      periodKey: currentMonth,
      title: 'Full Day Spa & Thermal Bath 🧖‍♀️',
      description: 'Grand monthly reward: Luxury relaxation day funded by the loser.',
      status: 'active',
      dueDate: today,
    },
  ];
}

export function getInitialState(): AppState {
  const today = getTodayDateString();
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  const yStr = `${yesterday.getFullYear()}-${String(yesterday.getMonth() + 1).padStart(2, '0')}-${String(yesterday.getDate()).padStart(2, '0')}`;

  return {
    activePlayerId: null, // Displays "Who are you?" on initial device load
    players: INITIAL_PLAYERS,
    habits: INITIAL_HABITS,
    checkIns: [
      // Maciek's recent check-ins
      {
        id: 'c-m1',
        habitId: 'maciek-sleep',
        playerId: 'maciek',
        date: yStr,
        pointsEarned: 50,
        completedAt: new Date(Date.now() - 86400000).toISOString(),
      },
      {
        id: 'c-m2',
        habitId: 'maciek-gym',
        playerId: 'maciek',
        date: yStr,
        pointsEarned: 40,
        completedAt: new Date(Date.now() - 80000000).toISOString(),
      },
      {
        id: 'c-m3',
        habitId: 'maciek-reading',
        playerId: 'maciek',
        date: yStr,
        pointsEarned: 20,
        quantity: 20,
        completedAt: new Date(Date.now() - 70000000).toISOString(),
      },
      {
        id: 'c-m4',
        habitId: 'maciek-sleep',
        playerId: 'maciek',
        date: today,
        pointsEarned: 50,
        completedAt: new Date(Date.now() - 3600000).toISOString(),
      },
      // Myrna's recent check-ins
      {
        id: 'c-y1',
        habitId: 'myrna-sleep',
        playerId: 'myrna',
        date: yStr,
        pointsEarned: 50,
        completedAt: new Date(Date.now() - 86400000).toISOString(),
      },
      {
        id: 'c-y2',
        habitId: 'myrna-sport',
        playerId: 'myrna',
        date: yStr,
        pointsEarned: 30,
        completedAt: new Date(Date.now() - 75000000).toISOString(),
      },
      {
        id: 'c-y3',
        habitId: 'myrna-reading',
        playerId: 'myrna',
        date: yStr,
        pointsEarned: 25,
        quantity: 25,
        completedAt: new Date(Date.now() - 65000000).toISOString(),
      },
      {
        id: 'c-y4',
        habitId: 'myrna-sleep',
        playerId: 'myrna',
        date: today,
        pointsEarned: 50,
        completedAt: new Date(Date.now() - 2500000).toISOString(),
      },
      {
        id: 'c-y5',
        habitId: 'myrna-mind',
        playerId: 'myrna',
        date: today,
        pointsEarned: 10,
        completedAt: new Date(Date.now() - 1500000).toISOString(),
      },
    ],
    stakes: getInitialStakes(),
  };
}
